GigTechMvc/Controllers/ForumController.cs
using GigTech.Shared;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Collections.Generic;

namespace GigTechMvc.Controllers
{
    public class ForumController : Controller
    {
        private readonly GigTechContext _context;

        public ForumController(GigTechContext injectedContext)
        {
            _context = injectedContext;
        }
        public IActionResult ForumIndex()
        {
            var posts = _context.ForumPosts                             
                                .OrderByDescending(post => post.CreationDate)
                                .ToList();
            return View("/Views/Pages/ForumPage.cshtml", posts);
        }
    
        public IActionResult FilterByCategory(int? categoryNumber)
        {
            List<ForumPost> posts;
            if (categoryNumber.HasValue)
            {
                posts = _context.ForumPosts
                                .Where(post => post.ThreadId == categoryNumber)
                                .OrderByDescending(post => post.CreationDate)                              
                                .ToList();
            }
            else
            {
                posts = _context.ForumPosts
                                .OrderByDescending(post => post.CreationDate)                              
                                .ToList();
            }
            return View("/Views/Pages/ForumPage.cshtml", posts);
        }

        [HttpPost]
        public IActionResult CreatePost(string title, string content, int threadId, string userEmail)
        {
            if (!string.IsNullOrEmpty(title) && !string.IsNullOrEmpty(content))
            {
                content = content.Replace("\n", "<br />");

                var forumPost = new ForumPost()
                {
                    Title = title,
                    Content = content,
                    CreationDate = DateTime.Now,
                    ThreadId = threadId,
                    UserEmail = userEmail, // Assuming you have some authentication system to get the current user ID
                };

                _context.ForumPosts.Add(forumPost);
                _context.SaveChanges();
                return RedirectToAction("ForumIndex");

            }
            return RedirectToAction("ForumIndex");
        }

        [HttpPost]
        public IActionResult AddReply(int postId, string replyContent , string userEmail)
        {
            var parentPost = _context.ForumPosts.FirstOrDefault(p => p.Id == postId);

            if (parentPost == null)
            {
                return NotFound();
            }
            replyContent = replyContent.Replace("\n", "<br />");

            var replyPost =new ForumThread()
            {
                Content = replyContent,
                CreationDate = DateTime.Now,
                UserEmail = userEmail,
                ForumPostId = parentPost.Id // Associate reply with parent post
            };

            _context.ForumThreads.Add(replyPost);
            _context.SaveChanges();

            return RedirectToAction("ForumIndex");
        }
        [HttpPost]
        public IActionResult EditPost(int postId, string newTitle, string newContent)
        {
            var post = _context.ForumPosts.FirstOrDefault(p => p.Id == postId);

            if (post == null)
            {
                return NotFound();
            }
            else
            {

                if (post.Title != newTitle || post.Content != newContent)
                {
                    post.Title = newTitle;
                    post.Content = newContent;
                    _context.SaveChanges();
                }
            }

            return RedirectToAction("ForumIndex");
        }

        [HttpPost]
        public IActionResult DeletePost(int postId)
        {
            var post = _context.ForumPosts.FirstOrDefault(p => p.Id == postId);
            if (post == null)
            {
                return NotFound();
            }

            var replyPosts = _context.ForumThreads.Where(p => p.ForumPostId == postId);
            _context.ForumThreads.RemoveRange(replyPosts);
            _context.ForumPosts.Remove(post);

            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(500, "An error occurred while deleting the post.");
            }

            return RedirectToAction("ForumIndex");
        }
        [HttpPost]
        public IActionResult DeleteReply(int replyId)
        {
            var replyPost = _context.ForumThreads.FirstOrDefault(p => p.Id == replyId);
            if (replyPost == null)
            {
                return NotFound();
            }
            _context.ForumThreads.Remove(replyPost);

            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(500, "An error occurred while deleting the post.");
            }

            return RedirectToAction("ForumIndex");
        }

        [HttpPost]
        public IActionResult EditReply(int replyId, string newContent)
        {
            var reply = _context.ForumThreads.FirstOrDefault(p => p.Id == replyId);

            if (reply == null)
            {
                return NotFound();

            }

            else
            {
                newContent = newContent.Replace("\n", "<br />");

                if (reply.Content != newContent)
                {
                    reply.Content = newContent;
                    _context.SaveChanges();
                }
            }

            return RedirectToAction("ForumIndex");
        }
    }
}

GigTechMvc/Controllers/ProductController.cs
using GigTech.Shared;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using GigTechMvc.Models;//ErrorViewModel
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Authorization; //Activity


namespace GigTechMvc.Controllers
{

    public class ProductController : Controller
    {
        public readonly GigTechContext db = new();
        public ProductController(GigTechContext injectedContext)
        {
            db = injectedContext;
        }
        [Authorize]

        public IActionResult Product()
        {

            return View("/Views/Pages/ProductPage.cshtml");
        }
        public async Task<IActionResult> ProductDetailPage(int? id)
        {

            Product? model = await db.Products.SingleOrDefaultAsync(p => p.ProductId == id);

            if (model is null)
            {
                return NotFound($"ProductId {id} not found.");
            }
            return View("/Views/Pages/ProductDetailPage.cshtml", model);
        }
        public IActionResult AddToCart(int? gameId, string customerId )
        {
            ShoppingCart shoppingcart = new ShoppingCart();


            Product? product = db.Products.FirstOrDefault(p => p.ProductId == gameId);
            shoppingcart.CustomerId = customerId;
            shoppingcart.ProductId = product.ProductId.ToString();
            shoppingcart.ProductName = product.Title;
            shoppingcart.ProductPrice = product.Price;


            db.ShoppingCart.Add(shoppingcart);

            db.SaveChanges();
            return View("/Views/Pages/ProductPage.cshtml");
        }
        [HttpPost]
        public IActionResult reviewcomment(string username, string title, string review, int gameid)
        {
            List<Gamereview> gamelist;
            gamelist = db.Gamereviews.ToList();
            int a = gamelist.Count;
            var createreview = new Gamereview()
            {
                CommentId = a + 1,
                Title = title,
                Username = username,
                Review = review,
                GameId = gameid // Associate review with game
            };

            db.Gamereviews.Add(createreview);
            db.SaveChanges();

            return View("/Views/Pages/ProductPage.cshtml");
        }
        public IActionResult FilterByGenre(string genre) {
            List<Product> games;
            if (genre != "")
            {
                games = db.Products
                                .Where(game => game.Category == genre)
                                .ToList();
            }
            else
            {
                games = db.Products
                                .ToList();
            }
            return View("/Views/Pages/ProductPage.cshtml", games);
        }

    }
}

GigTechMvc/Controllers/ShoppingCartController.cs
using GigTech.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace GigTechMvc.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly GigTechContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;

        public ShoppingCartController(GigTechContext dbContext, UserManager<IdentityUser> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        public async Task<string> RetrieveUserId()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            return currentUser?.Id;
        }

        [Authorize]
        public IActionResult ShoppingCart()
        {
            var shoppingCartItems = _dbContext.ShoppingCart.ToList();
            ViewBag.ShoppingCart = shoppingCartItems;
            return View("/Views/Pages/ShoppingCart.cshtml");
        }

        [HttpPost]
        public IActionResult RemoveCustomerCart(int customerId)
        {
            try
            {
                var cartItems = _dbContext.ShoppingCart.Where(item => item.CustomerId == customerId.ToString()).ToList();
                if (cartItems.Any())
                {
                    _dbContext.ShoppingCart.RemoveRange(cartItems);
                    _dbContext.SaveChanges();
                }
                return RedirectToAction("Index", "Home"); // Redirect to a relevant page after removal
            }
            catch (Exception ex)
            {
                return StatusCode(500, "An error occurred while removing the cart items: " + ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Pay()
        {
            try
            {
                // Hämta den aktuella användarens ID
                var currentUser = await _userManager.GetUserAsync(User);
                if (currentUser == null)
                {
                    return RedirectToAction("Index", "Home"); // Eller någon annan åtgärd du föredrar
                }

                // Hämta kunden från databasen
                var customer = await _dbContext.Customers.FirstOrDefaultAsync(c => c.Email == currentUser.Email);
                if (customer == null)
                {
                    return NotFound("User not found.");
                }

                // Hämta varukorgsobjekt för den aktuella användaren
                var shoppingCartItems = _dbContext.ShoppingCart
                    .Where(item => item.CustomerId == customer.CustomerId.ToString())
                    .ToList();

                // Beräkna totalpriset
                decimal totalPrice = (decimal)shoppingCartItems.Sum(item => item.ProductPrice);

                // Kontrollera om kunden har tillräckligt med pengar
                if (customer.VMoney < totalPrice)
                {
                    return BadRequest("Insufficient funds.");
                }

                // Uppdatera Games för kunden
                var games = string.Join(",", shoppingCartItems.Select(item => item.ProductId));
                customer.Games = string.IsNullOrEmpty(customer.Games) ? games : customer.Games + "," + games;

                // Dra av det totala priset från kundens vMoney
                customer.VMoney -= (int)totalPrice;

                // Ta bort varukorgsobjekt
                _dbContext.ShoppingCart.RemoveRange(shoppingCartItems);

                // Spara ändringar i databasen
                await _dbContext.SaveChangesAsync();

                return RedirectToAction("UserPage", "UserPage");
            }
            catch (Exception ex)
            {
                // Hantera undantag om det behövs
                return StatusCode(500, "An error occurred during payment: " + ex.Message);
            }
        }







        public IActionResult Receipt()
        {
            var orderDetails = _dbContext.OrderDetails.ToList();
            return View("/Views/Shared/Receipt.cshtml", orderDetails);
        }




    }
}

GigTechMvc/Controllers/SupportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using GigTech.Common.Views.Pages;
using GigTech.Shared;
using GigTechMvc.Models;
using System.Diagnostics;

namespace GigTechMvc.Controllers
{
	public class SupportController : Controller
	{
		string _spPg = "~/Views/Pages/SupportPages/";
		public GigTechContext _context = new GigTechContext();
		
        public IActionResult Index()
        {
            return View("~/Views/Pages/SupportPage.cshtml", new SupportPageModel());
        }

		[Authorize]
		public IActionResult AccountInfo() 
		{
			return View("~/Views/Pages/UserPage.cshtml");
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}

}

GigTechMvc/Views/Shared/Receipt.cshtml
@model IEnumerable<GigTech.Shared.OrderDetail>

<!DOCTYPE html>
<html>
<head>
    <title>Receipt</title>
</head>
<body>
    <div style="margin-top: 100px;">
    @foreach (var orderDetail in Model)
    {
        <h2>Order Details</h2>
        <p>Order ID: @orderDetail.Id</p>
        <p>Customer ID: @orderDetail.CustomerId</p>
        <p>Order Date: @orderDetail.OrderDate</p>
        <p>Total Amount: @orderDetail.TotalAmount</p>

        <ul>
            <li>Product ID: @orderDetail.ProductId, Product Price: @orderDetail.TotalAmount</li>
        </ul>
    }
    </div>
</body>
</html>

GigTechMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GigTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GigTechMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">GigTech</a>
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-controller" viewBox="0 0 16 16">
                <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1z" />
                <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729q.211.136.373.297c.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466s.34 1.78.364 2.606c.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527s-2.496.723-3.224 1.527c-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.3 2.3 0 0 1 .433-.335l-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a14 14 0 0 0-.748 2.295 12.4 12.4 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.4 12.4 0 0 0-.339-2.406 14 14 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27s-2.063.091-2.913.27" />
            </svg>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Product">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="ForumIndex">Forum</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Support" asp-action="Index">Support</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="UserPage" asp-action="UserPage">User Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="ShoppingCart">ShoppingCart</a>
                    </li>
                    <li class="nav-item">
                        <partial name="_LoginPartial" />
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Image Header-->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="d-flex flex-column h-100">
        <!-- FOOTER -->
        <footer class="w-100 py-4 flex-shrink-0">
            <div class="container py-4">
                <div class="row gy-4 gx-5">
                    <div class="col-lg-4 col-md-6">
                        <h5 class="h1 text-white">
                            GT
                            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-controller" viewBox="0 0 16 16">
                                <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1z" />
                                <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729q.211.136.373.297c.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466s.34 1.78.364 2.606c.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527s-2.496.723-3.224 1.527c-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.3 2.3 0 0 1 .433-.335l-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a14 14 0 0 0-.748 2.295 12.4 12.4 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.4 12.4 0 0 0-.339-2.406 14 14 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27s-2.063.091-2.913.27" />
                            </svg>
                        </h5>
                        <p class="small text-muted">Dive into a realm of endless possibilities where you can effortlessly discover, buy, and enjoy your beloved games. Unleash the excitement and let the adventure unfold! 🎮✨</p>
                        <p class="small text-muted mb-0">&copy; Copyrights. All rights reserved. <a class="text-primary" href="#">GigTech</a></p>
                    </div>
                    <div class="col-lg-2 col-md-6">
                        <h5 class="text-white mb-3">Quick links</h5>
                        <ul class="list-unstyled text-muted">
                            <li><a asp-controller="Home" asp-action="Index" style="color: #0c63e4">Home</a></li>
                            <li><a asp-controller="Product" asp-action="Product"style="color: #0c63e4">Products</a></li>
                            <li><a asp-controller="Forum" asp-action="ForumIndex" style="color: #0c63e4">Forum</a></li>
                            <li><a asp-controller="Home" asp-action="About" style="color: #0c63e4">About</a></li>
                            <li><a asp-controller="Support" asp-action="Index" style="color: #0c63e4">Support</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-6">
                        <h5 class="text-white mb-3">Connect with us</h5>
                        <ul class="list-unstyled text-muted">
                            <li>
                                <a href="https://www.facebook.com" style="color: #0c63e4"><i class="fab fa-facebook-f"></i> Facebook</a>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951" />
                                </svg>
                            </li>
                            <li>
                                <a href="https://www.twitter.com" style="color: #0c63e4"><i class="fab fa-twitter"></i> Twitter</a>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                                    <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z" />
                                </svg>
                            </li>
                            <li>
                                <a href="https://www.instagram.com" style="color: #0c63e4"><i class="fab fa-instagram"></i> Instagram</a>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
                                </svg>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com" style="color: #0c63e4"><i class="fab fa-linkedin"></i> LinkedIn</a>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z" />
                                </svg>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <h5 class="text-white mb-3">GigTech</h5>
                        <p class="small text-muted">Your gaming paradise! Explore, purchase, and download your favorite games hassle-free. Let the fun begin! 🎮✨</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <!-- scrip for carousel -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>